ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS customer_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(20),
  ADD COLUMN IF NOT EXISTS customer_email VARCHAR(150),
  ADD COLUMN IF NOT EXISTS city VARCHAR(100);
