ALTER TABLE boutiques
    ADD COLUMN IF NOT EXISTS enable_jax BOOLEAN DEFAULT FALSE;

ALTER TABLE boutiques
    ADD COLUMN IF NOT EXISTS enable_intigo BOOLEAN DEFAULT FALSE;

ALTER TABLE boutiques
    ADD COLUMN IF NOT EXISTS enable_adeex BOOLEAN DEFAULT FALSE;
