ALTER TABLE boutiques
    ADD COLUMN IF NOT EXISTS category VARCHAR(255);

ALTER TABLE boutiques
    ADD COLUMN IF NOT EXISTS country VARCHAR(255);

ALTER TABLE boutiques
    ADD COLUMN IF NOT EXISTS city VARCHAR(255);
